pub mod calc_spill_weight;
pub mod inst;
// pub mod phi_elimination;
pub mod pro_epi_inserter;
pub mod reg_coalescer;
pub mod regalloc;
pub mod replace_copy;
// pub mod validate_frame_index;
// pub mod replace_data;
// pub mod spiller;
pub mod inst_def;
pub mod register;
pub use super::frame_object;
